SNOWFLAKE_ACCOUNT_NAME  = "GIDBELP-KIB31224"
SNOWFLAKE_ORGANIZATION_NAME = "GIDBELP"
SNOWFLAKE_ROLE = "ACCOUNTADMIN"
SNOWFLAKE_USER = "SHR1234"
SNOWFLAKE_PASSWORD = "ASDWqwer1234@!"

new_warehouses = {
  SHRUTI_WH  = "Testing warehouse"
}
